# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_telegramIds.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'get_telegramIds.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15get_telegramIds.proto\"\x17\n\x15GetTelegramIdsRequest\"\x93\x01\n\x12VipTopProfileEntry\x12\x13\n\x0btelegram_id\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x01\x12\x14\n\x0crating_count\x18\x04 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12\x0e\n\x06gender\x18\x06 \x01(\x05\x12\x17\n\x0f\x63reated_at_unix\x18\x07 \x01(\x03\"?\n\x16GetTelegramIdsResponse\x12%\n\x08profiles\x18\x01 \x03(\x0b\x32\x13.VipTopProfileEntry2Z\n\x15GetTelegramIdsService\x12\x41\n\x0eGetTelegramIds\x12\x16.GetTelegramIdsRequest\x1a\x17.GetTelegramIdsResponseB\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_telegramIds_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_GETTELEGRAMIDSREQUEST']._serialized_start=25
  _globals['_GETTELEGRAMIDSREQUEST']._serialized_end=48
  _globals['_VIPTOPPROFILEENTRY']._serialized_start=51
  _globals['_VIPTOPPROFILEENTRY']._serialized_end=198
  _globals['_GETTELEGRAMIDSRESPONSE']._serialized_start=200
  _globals['_GETTELEGRAMIDSRESPONSE']._serialized_end=263
  _globals['_GETTELEGRAMIDSSERVICE']._serialized_start=265
  _globals['_GETTELEGRAMIDSSERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
