// <auto-generated />
using System;
using System.Collections.Generic;
using LooksRatingApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LooksRatingApi.Migrations
{
    [DbContext(typeof(LooksRatingDbContext))]
    [Migration("20260510195327_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LooksRatingApi.Models.ListSeasons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ListSeasons", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TelegramFileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId");

                    b.ToTable("PhotoSeason", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("TelegramFileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("TheBestWeekId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TheBestWeekId");

                    b.ToTable("PhotoUser", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhotoUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhotoUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListSeasonsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListSeasonsId");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.TheBestWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenderEnumed")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("City", "LooksRatingApi.Models.TheBestWeek.City#CityVo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("City");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TheBestWeek", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.TopPhotoSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GenderEnum")
                        .HasColumnType("integer");

                    b.Property<Guid>("PhotoSeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("City", "LooksRatingApi.Models.TopPhotoSeason.City#CityVo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("City");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PhotoSeasonId", "GenderEnum")
                        .IsUnique();

                    b.ToTable("TopPhotoSeason", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid>("PhotoUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TimesInTop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.ComplexProperty<Dictionary<string, object>>("City", "LooksRatingApi.Models.User.City#CityVo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("City");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PhotoUserId")
                        .IsUnique();

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSession", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.UserTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTicket", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoSeason", b =>
                {
                    b.HasOne("LooksRatingApi.Models.Season", "Season")
                        .WithMany("PhotoSeasons")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany("PhotoSeasons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoUser", b =>
                {
                    b.HasOne("LooksRatingApi.Models.TheBestWeek", null)
                        .WithMany("PhotoUsers")
                        .HasForeignKey("TheBestWeekId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LooksRatingApi.Models.Review", b =>
                {
                    b.HasOne("LooksRatingApi.Models.PhotoUser", "PhotoUser")
                        .WithMany()
                        .HasForeignKey("PhotoUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhotoUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.Season", b =>
                {
                    b.HasOne("LooksRatingApi.Models.ListSeasons", "ListSeasons")
                        .WithMany("Seasons")
                        .HasForeignKey("ListSeasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListSeasons");
                });

            modelBuilder.Entity("LooksRatingApi.Models.TheBestWeek", b =>
                {
                    b.HasOne("LooksRatingApi.Models.User", null)
                        .WithMany("TheBestWeeks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LooksRatingApi.Models.TopPhotoSeason", b =>
                {
                    b.HasOne("LooksRatingApi.Models.PhotoSeason", "PhotoSeason")
                        .WithMany("TopPhotoSeasons")
                        .HasForeignKey("PhotoSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoSeason");
                });

            modelBuilder.Entity("LooksRatingApi.Models.User", b =>
                {
                    b.HasOne("LooksRatingApi.Models.PhotoUser", "PhotoUser")
                        .WithOne("User")
                        .HasForeignKey("LooksRatingApi.Models.User", "PhotoUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoUser");
                });

            modelBuilder.Entity("LooksRatingApi.Models.UserSession", b =>
                {
                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.UserTicket", b =>
                {
                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany("UserTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.ListSeasons", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoSeason", b =>
                {
                    b.Navigation("TopPhotoSeasons");
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoUser", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("LooksRatingApi.Models.Season", b =>
                {
                    b.Navigation("PhotoSeasons");
                });

            modelBuilder.Entity("LooksRatingApi.Models.TheBestWeek", b =>
                {
                    b.Navigation("PhotoUsers");
                });

            modelBuilder.Entity("LooksRatingApi.Models.User", b =>
                {
                    b.Navigation("PhotoSeasons");

                    b.Navigation("Reviews");

                    b.Navigation("TheBestWeeks");

                    b.Navigation("UserTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
