// <auto-generated />
using System;
using System.Collections.Generic;
using LooksRatingApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LooksRatingApi.Migrations
{
    [DbContext(typeof(LooksRatingDbContext))]
    [Migration("20260616101838_ReviewMilestoneSnapshotSync")]
    partial class ReviewMilestoneSnapshotSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LooksRatingApi.Models.EventStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique();

                    b.ToTable("EventStores", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.ListSeasons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ListSeasons", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountStars")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderPaymentChargeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TelegramPaymentChargeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Payload")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("TelegramPaymentChargeId")
                        .IsUnique()
                        .HasFilter("\"TelegramPaymentChargeId\" IS NOT NULL");

                    b.HasIndex("UserId", "Status", "CreatedAt");

                    b.ToTable("PaymentOrder", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeNomination")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenderNomination")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("CityNomination", "LooksRatingApi.Models.PhotoProfile.CityNomination#CityVo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("City");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Status");

                    b.HasIndex("UserId", "SeasonId")
                        .IsUnique();

                    b.HasIndex("SeasonId", "GenderNomination", "AgeNomination");

                    b.ToTable("PhotoProfile", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoProfilePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PhotoProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TelegramFileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("PhotoProfileId");

                    b.HasIndex("PhotoProfileId", "SortOrder")
                        .IsUnique();

                    b.ToTable("PhotoProfilePhoto", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeNomination")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenderNomination")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PhotoProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TelegramFileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("CityNomination", "LooksRatingApi.Models.PhotoUser.CityNomination#CityVo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("City");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PhotoProfileId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId", "SeasonId");

                    b.ToTable("PhotoUser", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountStars")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ProductCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VipDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.RecomendationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("City", "LooksRatingApi.Models.RecomendationSettings.City#CityVo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("City");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RecomendationSettings", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PhotoProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhotoProfileId", "CreatedAt");

                    b.HasIndex("UserId", "PhotoProfileId")
                        .IsUnique();

                    b.ToTable("Review", null, t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating_Range", "\"Rating\" >= 1 AND \"Rating\" <= 10");
                        });
                });

            modelBuilder.Entity("LooksRatingApi.Models.ReviewMilestoneNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<long>("OwnerTelegramId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PhotoProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("PhotoProfileId", "CycleNumber")
                        .IsUnique();

                    b.ToTable("ReviewMilestoneNotifications", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListSeasonsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListSeasonsId");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.SparksWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("SparksCount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("SparksLedger", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.TheBestWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("WeekOfYear")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("City", "Year", "WeekOfYear")
                        .IsUnique();

                    b.ToTable("TheBestWeek", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountInTop")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSession", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.UserTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PhotoProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhotoUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhotoProfileId");

                    b.HasIndex("PhotoUserId");

                    b.HasIndex("UserId", "PhotoProfileId")
                        .IsUnique();

                    b.ToTable("UserTicket", (string)null);
                });

            modelBuilder.Entity("LooksRatingApi.Models.PaymentOrder", b =>
                {
                    b.HasOne("LooksRatingApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoProfile", b =>
                {
                    b.HasOne("LooksRatingApi.Models.Season", "Season")
                        .WithMany("PhotoProfiles")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany("PhotoProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoProfilePhoto", b =>
                {
                    b.HasOne("LooksRatingApi.Models.PhotoProfile", "PhotoProfile")
                        .WithMany("Photos")
                        .HasForeignKey("PhotoProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoProfile");
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoUser", b =>
                {
                    b.HasOne("LooksRatingApi.Models.PhotoProfile", "PhotoProfile")
                        .WithMany("LegacyPhotoUsers")
                        .HasForeignKey("PhotoProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LooksRatingApi.Models.Season", "Season")
                        .WithMany("PhotoUsers")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany("PhotoUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PhotoProfile");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.RecomendationSettings", b =>
                {
                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithOne("RecomendationSettings")
                        .HasForeignKey("LooksRatingApi.Models.RecomendationSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.Review", b =>
                {
                    b.HasOne("LooksRatingApi.Models.PhotoProfile", "PhotoProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("PhotoProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhotoProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.Season", b =>
                {
                    b.HasOne("LooksRatingApi.Models.ListSeasons", "ListSeasons")
                        .WithMany("Seasons")
                        .HasForeignKey("ListSeasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListSeasons");
                });

            modelBuilder.Entity("LooksRatingApi.Models.SparksWallet", b =>
                {
                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithOne("SparksWallet")
                        .HasForeignKey("LooksRatingApi.Models.SparksWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.UserSession", b =>
                {
                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.UserTicket", b =>
                {
                    b.HasOne("LooksRatingApi.Models.PhotoProfile", "PhotoProfile")
                        .WithMany("UserTickets")
                        .HasForeignKey("PhotoProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LooksRatingApi.Models.PhotoUser", null)
                        .WithMany("UserTickets")
                        .HasForeignKey("PhotoUserId");

                    b.HasOne("LooksRatingApi.Models.User", "User")
                        .WithMany("UserTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LooksRatingApi.Models.ListSeasons", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoProfile", b =>
                {
                    b.Navigation("LegacyPhotoUsers");

                    b.Navigation("Photos");

                    b.Navigation("Reviews");

                    b.Navigation("UserTickets");
                });

            modelBuilder.Entity("LooksRatingApi.Models.PhotoUser", b =>
                {
                    b.Navigation("UserTickets");
                });

            modelBuilder.Entity("LooksRatingApi.Models.Season", b =>
                {
                    b.Navigation("PhotoProfiles");

                    b.Navigation("PhotoUsers");
                });

            modelBuilder.Entity("LooksRatingApi.Models.User", b =>
                {
                    b.Navigation("PhotoProfiles");

                    b.Navigation("PhotoUsers");

                    b.Navigation("RecomendationSettings");

                    b.Navigation("Reviews");

                    b.Navigation("SparksWallet");

                    b.Navigation("UserTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
