# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: create_writing_off_sparks.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'create_writing_off_sparks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63reate_writing_off_sparks.proto\"l\n\x1d\x43reateWritingOffSparksRequest\x12\x13\n\x0btelegram_id\x18\x01 \x01(\x03\x12\x14\n\x0csparks_count\x18\x02 \x01(\x05\x12\x13\n\x0bstars_count\x18\x03 \x01(\x05\x12\x0b\n\x03key\x18\x04 \x01(\t\"B\n\x1e\x43reateWritingOffSparksResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2z\n\x1d\x43reateWritingOffSparksService\x12Y\n\x16\x43reateWritingOffSparks\x12\x1e.CreateWritingOffSparksRequest\x1a\x1f.CreateWritingOffSparksResponseB\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'create_writing_off_sparks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_CREATEWRITINGOFFSPARKSREQUEST']._serialized_start=35
  _globals['_CREATEWRITINGOFFSPARKSREQUEST']._serialized_end=143
  _globals['_CREATEWRITINGOFFSPARKSRESPONSE']._serialized_start=145
  _globals['_CREATEWRITINGOFFSPARKSRESPONSE']._serialized_end=211
  _globals['_CREATEWRITINGOFFSPARKSSERVICE']._serialized_start=213
  _globals['_CREATEWRITINGOFFSPARKSSERVICE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
