# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_gen import create_writing_off_sparks_pb2 as create__writing__off__sparks__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in create_writing_off_sparks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CreateWritingOffSparksServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWritingOffSparks = channel.unary_unary(
                '/CreateWritingOffSparksService/CreateWritingOffSparks',
                request_serializer=create__writing__off__sparks__pb2.CreateWritingOffSparksRequest.SerializeToString,
                response_deserializer=create__writing__off__sparks__pb2.CreateWritingOffSparksResponse.FromString,
                _registered_method=True)


class CreateWritingOffSparksServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateWritingOffSparks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreateWritingOffSparksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWritingOffSparks': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWritingOffSparks,
                    request_deserializer=create__writing__off__sparks__pb2.CreateWritingOffSparksRequest.FromString,
                    response_serializer=create__writing__off__sparks__pb2.CreateWritingOffSparksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CreateWritingOffSparksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CreateWritingOffSparksService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CreateWritingOffSparksService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWritingOffSparks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CreateWritingOffSparksService/CreateWritingOffSparks',
            create__writing__off__sparks__pb2.CreateWritingOffSparksRequest.SerializeToString,
            create__writing__off__sparks__pb2.CreateWritingOffSparksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
