# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: current_sparks_for_user.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'current_sparks_for_user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63urrent_sparks_for_user.proto\"B\n\x1b\x43urrentSparksForUserRequest\x12\x13\n\x0btelegram_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x63redit\x18\x02 \x01(\x08\"n\n\x1c\x43urrentSparksForUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12,\n\x06status\x18\x03 \x01(\x0e\x32\x1c.ChannelSubscribeBonusStatus*\xb6\x02\n\x1b\x43hannelSubscribeBonusStatus\x12*\n&CHANNEL_SUBSCRIBE_BONUS_STATUS_UNKNOWN\x10\x00\x12+\n\'CHANNEL_SUBSCRIBE_BONUS_STATUS_CREDITED\x10\x01\x12\x33\n/CHANNEL_SUBSCRIBE_BONUS_STATUS_ALREADY_CREDITED\x10\x02\x12\x31\n-CHANNEL_SUBSCRIBE_BONUS_STATUS_USER_NOT_FOUND\x10\x03\x12)\n%CHANNEL_SUBSCRIBE_BONUS_STATUS_FAILED\x10\x04\x12+\n\'CHANNEL_SUBSCRIBE_BONUS_STATUS_ELIGIBLE\x10\x05\x32r\n\x1b\x43urrentSparksForUserService\x12S\n\x14\x43urrentSparksForUser\x12\x1c.CurrentSparksForUserRequest\x1a\x1d.CurrentSparksForUserResponseB\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'current_sparks_for_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_CHANNELSUBSCRIBEBONUSSTATUS']._serialized_start=214
  _globals['_CHANNELSUBSCRIBEBONUSSTATUS']._serialized_end=524
  _globals['_CURRENTSPARKSFORUSERREQUEST']._serialized_start=33
  _globals['_CURRENTSPARKSFORUSERREQUEST']._serialized_end=99
  _globals['_CURRENTSPARKSFORUSERRESPONSE']._serialized_start=101
  _globals['_CURRENTSPARKSFORUSERRESPONSE']._serialized_end=211
  _globals['_CURRENTSPARKSFORUSERSERVICE']._serialized_start=526
  _globals['_CURRENTSPARKSFORUSERSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
