# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_unactive_users.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'get_unactive_users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18get_unactive_users.proto\"\x19\n\x17GetUnActiveUsersRequest\"0\n\x18GetUnActiveUsersResponse\x12\x14\n\x0ctelegram_ids\x18\x01 \x03(\x03\x32\x62\n\x17GetUnActiveUsersService\x12G\n\x10GetUnActiveUsers\x12\x18.GetUnActiveUsersRequest\x1a\x19.GetUnActiveUsersResponseB\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_unactive_users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_GETUNACTIVEUSERSREQUEST']._serialized_start=28
  _globals['_GETUNACTIVEUSERSREQUEST']._serialized_end=53
  _globals['_GETUNACTIVEUSERSRESPONSE']._serialized_start=55
  _globals['_GETUNACTIVEUSERSRESPONSE']._serialized_end=103
  _globals['_GETUNACTIVEUSERSSERVICE']._serialized_start=105
  _globals['_GETUNACTIVEUSERSSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
