# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_users_for_message.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'get_users_for_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bget_users_for_message.proto\"_\n\x19GetUsersForMessageRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12!\n\x19only_unsubscribed_channel\x18\x03 \x01(\x08\"\x7f\n\x1aGetUsersForMessageResponse\x12\x14\n\x0ctelegram_ids\x18\x01 \x03(\x03\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12\x15\n\rhas_next_page\x18\x05 \x01(\x08\x32j\n\x19GetUsersForMessageService\x12M\n\x12GetUsersForMessage\x12\x1a.GetUsersForMessageRequest\x1a\x1b.GetUsersForMessageResponseB\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_users_for_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_GETUSERSFORMESSAGEREQUEST']._serialized_start=31
  _globals['_GETUSERSFORMESSAGEREQUEST']._serialized_end=126
  _globals['_GETUSERSFORMESSAGERESPONSE']._serialized_start=128
  _globals['_GETUSERSFORMESSAGERESPONSE']._serialized_end=255
  _globals['_GETUSERSFORMESSAGESERVICE']._serialized_start=257
  _globals['_GETUSERSFORMESSAGESERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
