# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_gen import get_unactive_users_pb2 as get__unactive__users__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in get_unactive_users_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GetUnActiveUsersServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUnActiveUsers = channel.unary_unary(
                '/GetUnActiveUsersService/GetUnActiveUsers',
                request_serializer=get__unactive__users__pb2.GetUnActiveUsersRequest.SerializeToString,
                response_deserializer=get__unactive__users__pb2.GetUnActiveUsersResponse.FromString,
                _registered_method=True)


class GetUnActiveUsersServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetUnActiveUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetUnActiveUsersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUnActiveUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnActiveUsers,
                    request_deserializer=get__unactive__users__pb2.GetUnActiveUsersRequest.FromString,
                    response_serializer=get__unactive__users__pb2.GetUnActiveUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetUnActiveUsersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GetUnActiveUsersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GetUnActiveUsersService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUnActiveUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GetUnActiveUsersService/GetUnActiveUsers',
            get__unactive__users__pb2.GetUnActiveUsersRequest.SerializeToString,
            get__unactive__users__pb2.GetUnActiveUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
