# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_writing_off_sparks.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'get_writing_off_sparks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_gen import writing_off_sparks_common_pb2 as writing__off__sparks__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cget_writing_off_sparks.proto\x1a\x1fwriting_off_sparks_common.proto\";\n\x1aGetWritingOffSparksRequest\x12\x1d\n\x15writing_off_sparks_id\x18\x01 \x01(\t\"d\n\x1bGetWritingOffSparksResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x04item\x18\x03 \x01(\x0b\x32\x15.WritingOffSparksItem2n\n\x1aGetWritingOffSparksService\x12P\n\x13GetWritingOffSparks\x12\x1b.GetWritingOffSparksRequest\x1a\x1c.GetWritingOffSparksResponseB\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_writing_off_sparks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_GETWRITINGOFFSPARKSREQUEST']._serialized_start=65
  _globals['_GETWRITINGOFFSPARKSREQUEST']._serialized_end=124
  _globals['_GETWRITINGOFFSPARKSRESPONSE']._serialized_start=126
  _globals['_GETWRITINGOFFSPARKSRESPONSE']._serialized_end=226
  _globals['_GETWRITINGOFFSPARKSSERVICE']._serialized_start=228
  _globals['_GETWRITINGOFFSPARKSSERVICE']._serialized_end=338
# @@protoc_insertion_point(module_scope)
