# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_writings_off_sparks.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'get_writings_off_sparks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_gen import writing_off_sparks_common_pb2 as writing__off__sparks__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dget_writings_off_sparks.proto\x1a\x1fwriting_off_sparks_common.proto\"L\n\x1bGetWritingsOffSparksRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"\xb3\x01\n\x1cGetWritingsOffSparksResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12$\n\x05items\x18\x03 \x03(\x0b\x32\x15.WritingOffSparksItem\x12\x13\n\x0btotal_count\x18\x04 \x01(\x05\x12\x0c\n\x04page\x18\x05 \x01(\x05\x12\x11\n\tpage_size\x18\x06 \x01(\x05\x12\x15\n\rhas_next_page\x18\x07 \x01(\x08\x32r\n\x1bGetWritingsOffSparksService\x12S\n\x14GetWritingsOffSparks\x12\x1c.GetWritingsOffSparksRequest\x1a\x1d.GetWritingsOffSparksResponseB\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_writings_off_sparks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_GETWRITINGSOFFSPARKSREQUEST']._serialized_start=66
  _globals['_GETWRITINGSOFFSPARKSREQUEST']._serialized_end=142
  _globals['_GETWRITINGSOFFSPARKSRESPONSE']._serialized_start=145
  _globals['_GETWRITINGSOFFSPARKSRESPONSE']._serialized_end=324
  _globals['_GETWRITINGSOFFSPARKSSERVICE']._serialized_start=326
  _globals['_GETWRITINGSOFFSPARKSSERVICE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
