# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_gen import get_writings_off_sparks_pb2 as get__writings__off__sparks__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in get_writings_off_sparks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GetWritingsOffSparksServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWritingsOffSparks = channel.unary_unary(
                '/GetWritingsOffSparksService/GetWritingsOffSparks',
                request_serializer=get__writings__off__sparks__pb2.GetWritingsOffSparksRequest.SerializeToString,
                response_deserializer=get__writings__off__sparks__pb2.GetWritingsOffSparksResponse.FromString,
                _registered_method=True)


class GetWritingsOffSparksServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetWritingsOffSparks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetWritingsOffSparksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWritingsOffSparks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWritingsOffSparks,
                    request_deserializer=get__writings__off__sparks__pb2.GetWritingsOffSparksRequest.FromString,
                    response_serializer=get__writings__off__sparks__pb2.GetWritingsOffSparksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetWritingsOffSparksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GetWritingsOffSparksService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GetWritingsOffSparksService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWritingsOffSparks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GetWritingsOffSparksService/GetWritingsOffSparks',
            get__writings__off__sparks__pb2.GetWritingsOffSparksRequest.SerializeToString,
            get__writings__off__sparks__pb2.GetWritingsOffSparksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
