# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_gen import list_writing_off_sparks_cities_pb2 as list__writing__off__sparks__cities__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in list_writing_off_sparks_cities_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ListWritingOffSparksCitiesServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListWritingOffSparksCities = channel.unary_unary(
                '/ListWritingOffSparksCitiesService/ListWritingOffSparksCities',
                request_serializer=list__writing__off__sparks__cities__pb2.ListWritingOffSparksCitiesRequest.SerializeToString,
                response_deserializer=list__writing__off__sparks__cities__pb2.ListWritingOffSparksCitiesResponse.FromString,
                _registered_method=True)


class ListWritingOffSparksCitiesServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListWritingOffSparksCities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListWritingOffSparksCitiesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListWritingOffSparksCities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWritingOffSparksCities,
                    request_deserializer=list__writing__off__sparks__cities__pb2.ListWritingOffSparksCitiesRequest.FromString,
                    response_serializer=list__writing__off__sparks__cities__pb2.ListWritingOffSparksCitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListWritingOffSparksCitiesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListWritingOffSparksCitiesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ListWritingOffSparksCitiesService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListWritingOffSparksCities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListWritingOffSparksCitiesService/ListWritingOffSparksCities',
            list__writing__off__sparks__cities__pb2.ListWritingOffSparksCitiesRequest.SerializeToString,
            list__writing__off__sparks__cities__pb2.ListWritingOffSparksCitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
