# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: list_writing_off_sparks_cities.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'list_writing_off_sparks_cities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$list_writing_off_sparks_cities.proto\"#\n!ListWritingOffSparksCitiesRequest\"V\n\"ListWritingOffSparksCitiesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06\x63ities\x18\x03 \x03(\t2\x8a\x01\n!ListWritingOffSparksCitiesService\x12\x65\n\x1aListWritingOffSparksCities\x12\".ListWritingOffSparksCitiesRequest\x1a#.ListWritingOffSparksCitiesResponseB\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'list_writing_off_sparks_cities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_LISTWRITINGOFFSPARKSCITIESREQUEST']._serialized_start=40
  _globals['_LISTWRITINGOFFSPARKSCITIESREQUEST']._serialized_end=75
  _globals['_LISTWRITINGOFFSPARKSCITIESRESPONSE']._serialized_start=77
  _globals['_LISTWRITINGOFFSPARKSCITIESRESPONSE']._serialized_end=163
  _globals['_LISTWRITINGOFFSPARKSCITIESSERVICE']._serialized_start=166
  _globals['_LISTWRITINGOFFSPARKSCITIESSERVICE']._serialized_end=304
# @@protoc_insertion_point(module_scope)
