# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: update_status_writing_off_sparks.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'update_status_writing_off_sparks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&update_status_writing_off_sparks.proto\"g\n#UpdateStatusWritingOffSparksRequest\x12\x1d\n\x15writing_off_sparks_id\x18\x01 \x01(\t\x12!\n\x06status\x18\x02 \x01(\x0e\x32\x11.OutputStatusEnum\"H\n$UpdateStatusWritingOffSparksResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*m\n\x10OutputStatusEnum\x12\"\n\x1eOUTPUT_STATUS_ENUM_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\r\n\tCANCELLED\x10\x02\x12\r\n\tCONFIRMED\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x32\x92\x01\n#UpdateStatusWritingOffSparksService\x12k\n\x1cUpdateStatusWritingOffSparks\x12$.UpdateStatusWritingOffSparksRequest\x1a%.UpdateStatusWritingOffSparksResponseB\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'update_status_writing_off_sparks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_OUTPUTSTATUSENUM']._serialized_start=221
  _globals['_OUTPUTSTATUSENUM']._serialized_end=330
  _globals['_UPDATESTATUSWRITINGOFFSPARKSREQUEST']._serialized_start=42
  _globals['_UPDATESTATUSWRITINGOFFSPARKSREQUEST']._serialized_end=145
  _globals['_UPDATESTATUSWRITINGOFFSPARKSRESPONSE']._serialized_start=147
  _globals['_UPDATESTATUSWRITINGOFFSPARKSRESPONSE']._serialized_end=219
  _globals['_UPDATESTATUSWRITINGOFFSPARKSSERVICE']._serialized_start=333
  _globals['_UPDATESTATUSWRITINGOFFSPARKSSERVICE']._serialized_end=479
# @@protoc_insertion_point(module_scope)
