# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: writing_off_sparks_common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'writing_off_sparks_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_gen import update_status_writing_off_sparks_pb2 as update__status__writing__off__sparks__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fwriting_off_sparks_common.proto\x1a&update_status_writing_off_sparks.proto\"\xbf\x01\n\x14WritingOffSparksItem\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\x06status\x18\x02 \x01(\x0e\x32\x11.OutputStatusEnum\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x13\n\x0btelegram_id\x18\x04 \x01(\x03\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\x12\x14\n\x0csparks_count\x18\x06 \x01(\x05\x12\r\n\x05stars\x18\x07 \x01(\x05\x12\x1f\n\x17\x63reated_at_unix_seconds\x18\x08 \x01(\x03\x42\x12\xaa\x02\x0fLooksRatingGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'writing_off_sparks_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017LooksRatingGrpc'
  _globals['_WRITINGOFFSPARKSITEM']._serialized_start=76
  _globals['_WRITINGOFFSPARKSITEM']._serialized_end=267
# @@protoc_insertion_point(module_scope)
