"""Centralized inline callback payloads for predictable routing."""

PRIVILEGES_HUB = "privileges:hub"
PRIVILEGES_VIP = "privileges:vip"
PRIVILEGES_REFERRAL = "privileges:referral"

CHANNEL_SUBSCRIBE_CONFIRM = "channel_subscribe:confirm"
CHANNEL_SUBSCRIBE_SKIP = "channel_subscribe:skip"

CHANNEL_SUBSCRIBE_STATUS_CREDITED = "CHANNEL_SUBSCRIBE_BONUS_STATUS_CREDITED"
CHANNEL_SUBSCRIBE_STATUS_ALREADY_CREDITED = "CHANNEL_SUBSCRIBE_BONUS_STATUS_ALREADY_CREDITED"
CHANNEL_SUBSCRIBE_STATUS_USER_NOT_FOUND = "CHANNEL_SUBSCRIBE_BONUS_STATUS_USER_NOT_FOUND"
CHANNEL_SUBSCRIBE_STATUS_FAILED = "CHANNEL_SUBSCRIBE_BONUS_STATUS_FAILED"
CHANNEL_SUBSCRIBE_STATUS_ELIGIBLE = "CHANNEL_SUBSCRIBE_BONUS_STATUS_ELIGIBLE"

SHOP_VIP_BUY = "shop:vip:buy"
SHOP_GIFTS = "shop:gifts"
SHOP_BACK = "shop:back"
SHOP_MAIN_MENU = "shop:menu"
